[tool.poetry]
name = "rando-ga-test-harness"
version = "0.1.0"
description = ""
authors = ["The Randalorian <dwjgame11@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
